autoload -U compinit
compinit -u
setopt nonomatch
setopt RM_STAR_SILENT

export LANG=en_US.UTF-8

# Homebrew(silicon)
export PATH="/opt/homebrew/bin:$PATH"
export PATH="$(brew --prefix openssl)/bin:$PATH"

# GNU
export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"

# Java
export JAVA_HOME="$HOME/.sdkman/candidates/java/current"
export PATH="$JAVA_HOME/bin:$PATH"

# Android
export ANDROID_SDK_ROOT="$HOME/Library/Android/sdk"
export PATH="$ANDROID_SDK_ROOT/tools/bin:$PATH"
export PATH="$ANDROID_SDK_ROOT/platform-tools:$PATH"
export PATH="$ANDROID_SDK_ROOT/emulator:$PATH"
export PATH="$ANDROID_SDK_ROOT/build-tools:$PATH"

# Ruby
RUBY_DIR="$(brew --prefix ruby)"
export PATH="$RUBY_DIR/bin:$PATH"
export LDFLAGS="-L$RUBY_DIR/lib"
export CPPFLAGS="-I$RUBY_DIR/include"
export PKG_CONFIG_PATH="$RUBY_DIR/lib/pkgconfig"
## gem
GEM_DIR="$(gem environment | grep '\- INSTALLATION DIRECTORY:' | awk '{print $4}')"
export PATH="$GEM_DIR/bin:$PATH"

# env
eval "$(nodenv init -)"

# SDKMAN!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# zshrc
[[ -s "$HOME/.zshrc" ]] && source "$HOME/.zshrc"
