autoload -U compinit
compinit -u
setopt nonomatch
setopt RM_STAR_SILENT

export LANG=en_US.UTF-8

# Homebrew(silicon)
BREW_PREFIX=/opt/homebrew
export PATH="$BREW_PREFIX/bin:$PATH"

# GNU
export PATH="$BREW_PREFIX/opt/coreutils/libexec/gnubin:$PATH"

# Java
export JAVA_HOME="$HOME/.sdkman/candidates/java/current"
export PATH="$JAVA_HOME/bin:$PATH"

# Android
export ANDROID_SDK_ROOT="$HOME/Library/Android/sdk"
export PATH="$ANDROID_SDK_ROOT/tools/bin:$PATH"
export PATH="$ANDROID_SDK_ROOT/platform-tools:$PATH"
export PATH="$ANDROID_SDK_ROOT/emulator:$PATH"
export PATH="$ANDROID_SDK_ROOT/build-tools:$PATH"

# env
eval "$(anyenv init -)"

# zshrc
[[ -s "$HOME/.zshrc" ]] && source "$HOME/.zshrc"
